### PR TITLE
Add Delete Pv functionality and other fixes

### LINKED ISSUE #6: Support automatic cleanup of deleted volumes
DLPP currently assumes that persistent volume recovery is a manual process handled by the storage operator, and the PV resource in the K8s API server is only deleted once the associated "disk" is properly backed up, and removed.
This is the proper handling when the volume's ReclaimPolicy is set to Retain.
However, when it is set to Delete users can reasonably expect the storage manger service to handle the cleanup.

DLPP should listen to "DELETE PV" events. When a PV is deleted with policy set to Delete DLPP should automaticaly destroy the directory associated with the PV, cleanup all mount points and quotas, and should free the disk's capacity in the K8s API server.

### PR DESCRIPTION
**Pull request by balintTobik**

### CODE REVIEW

File: cmd/provisioner/provisioner.go [hunk 1]
```diff
@@ -67,14 +67,14 @@ func main() {
 
 func (provisioner *Provisoner) pvcAdded(pvc v1.PersistentVolumeClaim) {
 	_, nodeNameOk := pvc.ObjectMeta.Annotations[k8sclient.NodeName]
-	if pvc.ObjectMeta.Annotations[k8sclient.LocalAnnotation] == k8sclient.LocalScProvisioner && !nodeNameOk && (pvc.Status.Phase != v1.ClaimBound) {
+	if pvc.ObjectMeta.Annotations[k8sclient.LocalAnnotation] == k8sclient.LocalScProvisioner && !nodeNameOk && (pvc.Status.Phase == v1.ClaimPending) {
```
Comment (Levovar) [inline cmd/provisioner/provisioner.go]: could make this condition into a bool function to avoid these copy paste mistakes in the future

File: pkg/handlers/pvchandler.go [hunk 2]
```diff
@@ -78,28 +79,40 @@ func (pvcHandler *PvcHandler) pvcChanged(oldPvc v1.PersistentVolumeClaim, newPvc
 	pvcHandler.createPVStorage(newPvc, pvDirPath)
 }
 
+func (pvcHandler *PvcHandler) pvcDeleted(pvc v1.PersistentVolumeClaim) {
+	if handlePvc, _ := shouldPvcBeHandled(v1.PersistentVolumeClaim{}, pvc, pvcHandler.nodeName, pvcHandler.storagePath); handlePvc {
+		pv, err := k8sclient.GetVolume(pvc.Spec.VolumeName, pvcHandler.k8sClient)
+		if err != nil {
```
Comment (Levovar) [inline pkg/handlers/pvchandler.go:84]: aren't you missing a return here?

File: pkg/handlers/pvchandler.go [hunk 3]
```diff
@@ -78,28 +79,40 @@ func (pvcHandler *PvcHandler) pvcChanged(oldPvc v1.PersistentVolumeClaim, newPvc
...
-			if pvcNodeName, ok := newPvc.ObjectMeta.Annotations[k8sclient.NodeName]; ok && (pvcNodeName == nodeName) {
-				pvDir := storagePath + "/" + newPvc.ObjectMeta.Namespace + "_" + newPvc.ObjectMeta.Name + "-" + generateRandomSuffix(8)
+	if newPvc.Annotations[k8sclient.LocalAnnotation] == k8sclient.LocalScProvisioner && isChangeEnoughToProceed(oldPvc, newPvc) {
+		if pvcNodeName, ok := newPvc.ObjectMeta.Annotations[k8sclient.NodeName]; ok && pvcNodeName == nodeName {
+			if newPvc.Status.Phase == v1.ClaimPending {
+				pvDir := storagePath + newPvc.ObjectMeta.Namespace + "_" + newPvc.ObjectMeta.Name + "-" + generateRandomSuffix(8)
 				if _, err := os.Stat(pvDir); os.IsNotExist(err) {
 					return true, pvDir
 				}
+			} else if newPvc.Status.Phase == v1.ClaimBound && newPvc.Spec.VolumeName != "" {
```
Comment (Levovar) [inline pkg/handlers/pvchandler.go]: won't this negatively affect the new PVC added / modify cases though?
it mightb eb etter to create a new checket function for delete only re-using parts of the existing conitions, rather than forcing both cases through the same condition

File: pkg/handlers/pvchandler.go [hunk 4]
```diff
@@ -111,88 +124,161 @@ func (pvcHandler *PvcHandler) createPVStorage(pvc v1.PersistentVolumeClaim, pvDi
...
 	bindMountCommand := fmt.Sprintf("%[1]s %[1]s none bind 0 0\n", pvDirPath)
 	_, err = file.WriteString(bindMountCommand)
 	if err != nil {
-		log.Println("ERROR: Cannot modify fstab file: " + fstabPath + " because: " + err.Error() + "\nCannot save mountpoint!")
+		log.Println("PvcHandler ERROR: Cannot modify fstab file: " + fstabPath + " because: " + err.Error() + "\nCannot save mountpoint!")
+		return
+	}
+}
+
+func removePvDataFromFile(filePath string, searchData string) error {
```
Comment (Levovar) [inline pkg/handlers/pvchandler.go]: better readability if you include functions in the order they are called, i.e. this after deletePVStorage

File: pkg/handlers/pvchandler.go [hunk 5]
```diff
@@ -111,88 +124,161 @@ func (pvcHandler *PvcHandler) createPVStorage(pvc v1.PersistentVolumeClaim, pvDi
...
+	}
+	localVolumePath := pv.Spec.Local.Path
+	// unmount pv directory
+	err := syscall.Unmount(localVolumePath, 0)
+	if err != nil {
+		log.Println("PvcHandler ERROR: Cannot UNMOUNT directory (" + localVolumePath + "), because: " + err.Error())
+		return
+	}
+	// delete xfs_quota data
+	subcommand := fmt.Sprintf("limit -p bsoft=0 bhard=0 %s", filepath.Base(localVolumePath))
```
Comment (Levovar) [inline pkg/handlers/pvchandler.go:234]: is this really needed? you simply delete the directory anyway later on, right?

File: pkg/handlers/pvchandler.go [hunk 6]
```diff
@@ -111,88 +124,161 @@ func (pvcHandler *PvcHandler) createPVStorage(pvc v1.PersistentVolumeClaim, pvDi
...
+	}
+	defer file.Close()
+	_, err = file.WriteString(strings.Join(removedList, "\n"))
+	if err != nil {
+		return errors.New("Cannot modify" + filePath + " file, because: " + err.Error())
+	}
+	return nil
+}
+
+func deletePVStorage(pv v1.PersistentVolume, storagePath string){
```
Comment (Levovar) [inline pkg/handlers/pvchandler.go:222]: I don't think it is a good design to release physical attributes asynchronously in two different handlers
the PVC handler should not deal with the physical attributes of the PV - just delete the PV.
PV handler will recognize the PV is deleted, and can execute all unmounting and deletion operations, all at once

File: pkg/k8sclient/k8sclient.go [hunk 7]
```diff
@@ -35,37 +36,52 @@ func GetNodeByLabel(label string, kubeClient kubernetes.Interface) (v1.Node, err
...
 func UpdateNodeStatus(nodeName string, kubeClient kubernetes.Interface, node *v1.Node) error {
-	_, err := kubeClient.CoreV1().Nodes().UpdateStatus(node)
+	_, err := kubeClient.CoreV1().Nodes().UpdateStatus(context.TODO(), node, metav1.UpdateOptions{})
 	if err != nil {
 		return err
 	}
 	return nil
 }
+
+func StorageClassIsNokiaLocal(storageClassName string, kubeClient kubernetes.Interface) (bool, error){
```
Comment (Levovar) [inline pkg/k8sclient/k8sclient.go:76]: shoudnt this be added to the pvchandler entry criteria list too? after all we should do nothing on any level with a resource not belonging to us

**Review by Levovar — CHANGES_REQUESTED** [review]

File: pkg/handlers/pvchandler.go (hunk 5 above)
Comment (balintTobik) [reply pkg/handlers/pvchandler.go:234]: Yes, but setting limits to 0 and project -C command needs to delete project from metadata. 
It's not must have, but without it, many entries remain in metadata. Can be seen in xfs_quota report.

File: pkg/k8sclient/k8sclient.go (hunk 7 above)
Comment (balintTobik) [reply pkg/k8sclient/k8sclient.go:76]: Pvcs have annotation "volume.beta.kubernetes.io/storage-provisioner" which is contains the provisoner of the storage-class. In our case it is "nokia.k8s.io/local". Pvs only have storagclass name.
Should I change to both check the storageclass name?

Comment (Levovar) [reply pkg/k8sclient/k8sclient.go:76]: would be good if the solution wouldn't depend on beta APIs IMO

File: pkg/handlers/pvchandler.go (hunk 6 above)
Comment (balintTobik) [reply pkg/handlers/pvchandler.go:222]: Yeah, It was the first try. But if every delete command applied in the pvhandler, sig-storage will recreate some pvs, in case deleting many pvcs at once.
Pvhandler cannot umount fast enough, and sig-storage rediscover path and mountpoint and recreate pv.

Comment (Levovar) [reply pkg/handlers/pvchandler.go:222]: make PVhandler multi-threaded? :)

Comment (Levovar) [reply pkg/handlers/pvchandler.go:222]: but okay, dont want to torture you. a TODO is enough for now, that this should be relocated to PV Handler, and if PVs were recreated even when processing is happening in multiple threads, then it should be deleted post umount

Comment (balintTobik) [reply pkg/handlers/pvchandler.go:222]: Thanks! :)

**Review by Levovar — APPROVED** [review]
